package env

import "os"

var (
	BUILDKITE = os.Getenv("BUILDKITE")

	BUILDKITE_AGENT_ACCESS_TOKEN = os.Getenv("BUILDKITE_AGENT_ACCESS_TOKEN")

	BUILDKITE_AGENT_DEBUG = os.Getenv("BUILDKITE_AGENT_DEBUG")

	BUILDKITE_AGENT_DISCONNECT_AFTER_JOB = os.Getenv("BUILDKITE_AGENT_DISCONNECT_AFTER_JOB")

	BUILDKITE_AGENT_DISCONNECT_AFTER_IDLE_TIMEOUT = os.Getenv("BUILDKITE_AGENT_DISCONNECT_AFTER_IDLE_TIMEOUT")

	BUILDKITE_AGENT_ENDPOINT = os.Getenv("BUILDKITE_AGENT_ENDPOINT")

	BUILDKITE_AGENT_EXPERIMENT = os.Getenv("BUILDKITE_AGENT_EXPERIMENT")

	BUILDKITE_AGENT_HEALTH_CHECK_ADDR = os.Getenv("BUILDKITE_AGENT_HEALTH_CHECK_ADDR")

	BUILDKITE_AGENT_ID = os.Getenv("BUILDKITE_AGENT_ID")

	BUILDKITE_AGENT_META_DATA_ = os.Getenv("BUILDKITE_AGENT_META_DATA_")

	BUILDKITE_AGENT_NAME = os.Getenv("BUILDKITE_AGENT_NAME")

	BUILDKITE_AGENT_PID = os.Getenv("BUILDKITE_AGENT_PID")

	BUILDKITE_ARTIFACT_PATHS = os.Getenv("BUILDKITE_ARTIFACT_PATHS")

	BUILDKITE_ARTIFACT_UPLOAD_DESTINATION = os.Getenv("BUILDKITE_ARTIFACT_UPLOAD_DESTINATION")

	BUILDKITE_BIN_PATH = os.Getenv("BUILDKITE_BIN_PATH")

	BUILDKITE_BRANCH = os.Getenv("BUILDKITE_BRANCH")

	BUILDKITE_BUILD_CHECKOUT_PATH = os.Getenv("BUILDKITE_BUILD_CHECKOUT_PATH")

	BUILDKITE_BUILD_AUTHOR = os.Getenv("BUILDKITE_BUILD_AUTHOR")

	BUILDKITE_BUILD_AUTHOR_EMAIL = os.Getenv("BUILDKITE_BUILD_AUTHOR_EMAIL")

	BUILDKITE_BUILD_CREATOR = os.Getenv("BUILDKITE_BUILD_CREATOR")

	BUILDKITE_BUILD_CREATOR_EMAIL = os.Getenv("BUILDKITE_BUILD_CREATOR_EMAIL")

	BUILDKITE_BUILD_CREATOR_TEAMS = os.Getenv("BUILDKITE_BUILD_CREATOR_TEAMS")

	BUILDKITE_BUILD_ID = os.Getenv("BUILDKITE_BUILD_ID")

	BUILDKITE_BUILD_NUMBER = os.Getenv("BUILDKITE_BUILD_NUMBER")

	BUILDKITE_BUILD_PATH = os.Getenv("BUILDKITE_BUILD_PATH")

	BUILDKITE_BUILD_URL = os.Getenv("BUILDKITE_BUILD_URL")

	BUILDKITE_CANCEL_GRACE_PERIOD = os.Getenv("BUILDKITE_CANCEL_GRACE_PERIOD")

	BUILDKITE_CANCEL_SIGNAL = os.Getenv("BUILDKITE_CANCEL_SIGNAL")

	BUILDKITE_CLEAN_CHECKOUT = os.Getenv("BUILDKITE_CLEAN_CHECKOUT")

	BUILDKITE_COMMAND = os.Getenv("BUILDKITE_COMMAND")

	BUILDKITE_COMMAND_EVAL = os.Getenv("BUILDKITE_COMMAND_EVAL")

	BUILDKITE_COMMAND_EXIT_STATUS = os.Getenv("BUILDKITE_COMMAND_EXIT_STATUS")

	BUILDKITE_COMMIT = os.Getenv("BUILDKITE_COMMIT")

	BUILDKITE_CONFIG_PATH = os.Getenv("BUILDKITE_CONFIG_PATH")

	BUILDKITE_ENV_FILE = os.Getenv("BUILDKITE_ENV_FILE")

	BUILDKITE_GIT_CLEAN_FLAGS = os.Getenv("BUILDKITE_GIT_CLEAN_FLAGS")

	BUILDKITE_GIT_CLONE_FLAGS = os.Getenv("BUILDKITE_GIT_CLONE_FLAGS")

	BUILDKITE_GIT_SUBMODULES = os.Getenv("BUILDKITE_GIT_SUBMODULES")

	BUILDKITE_GITHUB_DEPLOYMENT_ID = os.Getenv("BUILDKITE_GITHUB_DEPLOYMENT_ID")

	BUILDKITE_GITHUB_DEPLOYMENT_ENVIRONMENT = os.Getenv("BUILDKITE_GITHUB_DEPLOYMENT_ENVIRONMENT")

	BUILDKITE_GITHUB_DEPLOYMENT_TASK = os.Getenv("BUILDKITE_GITHUB_DEPLOYMENT_TASK")

	BUILDKITE_GITHUB_DEPLOYMENT_PAYLOAD = os.Getenv("BUILDKITE_GITHUB_DEPLOYMENT_PAYLOAD")

	BUILDKITE_HOOKS_PATH = os.Getenv("BUILDKITE_HOOKS_PATH")

	BUILDKITE_IGNORED_ENV = os.Getenv("BUILDKITE_IGNORED_ENV")

	BUILDKITE_JOB_ID = os.Getenv("BUILDKITE_JOB_ID")

	BUILDKITE_JOB_LOG_TMPFILE = os.Getenv("BUILDKITE_JOB_LOG_TMPFILE")

	BUILDKITE_LABEL = os.Getenv("BUILDKITE_LABEL")

	BUILDKITE_LAST_HOOK_EXIT_STATUS = os.Getenv("BUILDKITE_LAST_HOOK_EXIT_STATUS")

	BUILDKITE_LOCAL_HOOKS_ENABLED = os.Getenv("BUILDKITE_LOCAL_HOOKS_ENABLED")

	BUILDKITE_MESSAGE = os.Getenv("BUILDKITE_MESSAGE")

	BUILDKITE_ORGANIZATION_SLUG = os.Getenv("BUILDKITE_ORGANIZATION_SLUG")

	BUILDKITE_PARALLEL_JOB = os.Getenv("BUILDKITE_PARALLEL_JOB")

	BUILDKITE_PARALLEL_JOB_COUNT = os.Getenv("BUILDKITE_PARALLEL_JOB_COUNT")

	BUILDKITE_PIPELINE_DEFAULT_BRANCH = os.Getenv("BUILDKITE_PIPELINE_DEFAULT_BRANCH")

	BUILDKITE_PIPELINE_NAME = os.Getenv("BUILDKITE_PIPELINE_NAME")

	BUILDKITE_PIPELINE_PROVIDER = os.Getenv("BUILDKITE_PIPELINE_PROVIDER")

	BUILDKITE_PIPELINE_SLUG = os.Getenv("BUILDKITE_PIPELINE_SLUG")

	BUILDKITE_PLUGINS = os.Getenv("BUILDKITE_PLUGINS")

	BUILDKITE_PLUGINS_ENABLED = os.Getenv("BUILDKITE_PLUGINS_ENABLED")

	BUILDKITE_PLUGINS_PATH = os.Getenv("BUILDKITE_PLUGINS_PATH")

	BUILDKITE_PLUGIN_VALIDATION = os.Getenv("BUILDKITE_PLUGIN_VALIDATION")

	BUILDKITE_PULL_REQUEST = os.Getenv("BUILDKITE_PULL_REQUEST")

	BUILDKITE_PULL_REQUEST_BASE_BRANCH = os.Getenv("BUILDKITE_PULL_REQUEST_BASE_BRANCH")

	BUILDKITE_PULL_REQUEST_DRAFT = os.Getenv("BUILDKITE_PULL_REQUEST_DRAFT")

	BUILDKITE_PULL_REQUEST_REPO = os.Getenv("BUILDKITE_PULL_REQUEST_REPO")

	BUILDKITE_REBUILT_FROM_BUILD_ID = os.Getenv("BUILDKITE_REBUILT_FROM_BUILD_ID")

	BUILDKITE_REBUILT_FROM_BUILD_NUMBER = os.Getenv("BUILDKITE_REBUILT_FROM_BUILD_NUMBER")

	BUILDKITE_REFSPEC = os.Getenv("BUILDKITE_REFSPEC")

	BUILDKITE_REPO = os.Getenv("BUILDKITE_REPO")

	BUILDKITE_REPO_MIRROR = os.Getenv("BUILDKITE_REPO_MIRROR")

	BUILDKITE_RETRY_COUNT = os.Getenv("BUILDKITE_RETRY_COUNT")

	BUILDKITE_S3_ACCESS_KEY_ID = os.Getenv("BUILDKITE_S3_ACCESS_KEY_ID")

	BUILDKITE_S3_ACCESS_URL = os.Getenv("BUILDKITE_S3_ACCESS_URL")

	BUILDKITE_S3_ACL = os.Getenv("BUILDKITE_S3_ACL")

	BUILDKITE_S3_DEFAULT_REGION = os.Getenv("BUILDKITE_S3_DEFAULT_REGION")

	BUILDKITE_S3_SECRET_ACCESS_KEY = os.Getenv("BUILDKITE_S3_SECRET_ACCESS_KEY")

	BUILDKITE_S3_SSE_ENABLED = os.Getenv("BUILDKITE_S3_SSE_ENABLED")

	BUILDKITE_SHELL = os.Getenv("BUILDKITE_SHELL")

	BUILDKITE_SOURCE = os.Getenv("BUILDKITE_SOURCE")

	BUILDKITE_SSH_KEYSCAN = os.Getenv("BUILDKITE_SSH_KEYSCAN")

	BUILDKITE_STEP_ID = os.Getenv("BUILDKITE_STEP_ID")

	BUILDKITE_STEP_KEY = os.Getenv("BUILDKITE_STEP_KEY")

	BUILDKITE_TAG = os.Getenv("BUILDKITE_TAG")

	BUILDKITE_TIMEOUT = os.Getenv("BUILDKITE_TIMEOUT")

	BUILDKITE_TRACING_BACKEND = os.Getenv("BUILDKITE_TRACING_BACKEND")

	BUILDKITE_TRIGGERED_FROM_BUILD_ID = os.Getenv("BUILDKITE_TRIGGERED_FROM_BUILD_ID")

	BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER = os.Getenv("BUILDKITE_TRIGGERED_FROM_BUILD_NUMBER")

	BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG = os.Getenv("BUILDKITE_TRIGGERED_FROM_BUILD_PIPELINE_SLUG")

	BUILDKITE_UNBLOCKER = os.Getenv("BUILDKITE_UNBLOCKER")

	BUILDKITE_UNBLOCKER_EMAIL = os.Getenv("BUILDKITE_UNBLOCKER_EMAIL")

	BUILDKITE_UNBLOCKER_ID = os.Getenv("BUILDKITE_UNBLOCKER_ID")

	BUILDKITE_UNBLOCKER_TEAMS = os.Getenv("BUILDKITE_UNBLOCKER_TEAMS")

	CI = os.Getenv("CI")
)
